global:
  scrape_interval: 5s 

scrape_configs:
  # Add this job to scrape internal Prometheus metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8000']

  - job_name: 'post-service'
    static_configs:
      - targets: ['post-service:8001']