events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        # Povečamo dovoljeno velikost naloženih datotek na 100 MB
        client_max_body_size 100M;

        # 1. Usmerjanje prometa za FRONTEND
        location / {
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Usmerjanje prometa za User Service
        location /api/users {
            proxy_pass http://user-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Usmerjanje prometa za Post Service
        location /api/posts {
            proxy_pass http://post-service:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}