version = 5.6.0
archive_dir = /etc/letsencrypt/archive/nuks.v4.si
cert = /etc/letsencrypt/live/nuks.v4.si/cert.pem
privkey = /etc/letsencrypt/live/nuks.v4.si/privkey.pem
chain = /etc/letsencrypt/live/nuks.v4.si/chain.pem
fullchain = /etc/letsencrypt/live/nuks.v4.si/fullchain.pem
[renewalparams]
account = a9d917a2af25f4fa738a297e286714ad
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
